// Generated by tools/gen_pet_assets.py - do not edit by hand.
// Source atlas: spritesheet.webp (v2, 1536x2288, 8x11)
// Frames: 57   Blob: 2551288 bytes
#pragma once

#include <stdint.h>

#ifndef PET_ATLAS_SOPHIE_PORTRAIT_H
#define PET_ATLAS_SOPHIE_PORTRAIT_H

// Union of every frame crop inside the 192x208 atlas cell. The UI keeps a
// single image object this size, so the invalidated area stays constant
// while the per-frame offset moves the actual pixels inside it.
#define PET_ATLAS_CELL_W        192
#define PET_ATLAS_CELL_H        208
#define PET_ATLAS_STAGE_X       31
#define PET_ATLAS_STAGE_Y       5
#define PET_ATLAS_STAGE_W       129
#define PET_ATLAS_STAGE_H       198

// RGB565A8: 2 字节颜色平面 + 1 字节 alpha 平面。
#define PET_ATLAS_BYTES_PER_PIXEL 3

#define PET_ATLAS_BLOB_SIZE 2551288

typedef struct {
    uint32_t offset;   // byte offset of the RGB565A8 frame inside the blob
    int16_t  x;        // crop origin inside the 192x208 atlas cell
    int16_t  y;
    int16_t  w;
    int16_t  h;
    uint16_t duration; // frame duration in ms
} pet_atlas_frame_t;

typedef struct {
    const char       *name;
    uint16_t          first;   // index of the first frame
    uint16_t          count;
    const pet_atlas_frame_t *frames;
} pet_atlas_state_t;

#define PET_ATLAS_STATE_COUNT 9
#define PET_ATLAS_FRAME_COUNT 57

extern const pet_atlas_state_t PET_ATLAS_STATES[PET_ATLAS_STATE_COUNT];

#endif  // PET_ATLAS_SOPHIE_PORTRAIT_H
