#!/usr/bin/env python3
"""Extract per-frame sprites from a v2 ChatGPT/Codex pet atlas.

Input : a v2 atlas (1536x2288 WebP/PNG, 8 columns x 11 rows, 192x208 cells).
Output: a packed RGB565A8 blob embedded into the firmware plus a generated C
        header holding the frame table.

Why per-frame tight crops instead of whole 192x208 cells:
  the character only occupies 54-129 px of the 192 px cell width, so cropping
  to the non-transparent bounding box (and remembering the crop offset) keeps
  the rendered result pixel-identical to the atlas while cutting flash use by
  roughly 3x.  The offset is applied at draw time, so the character does not
  move relative to the atlas grid.
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path

from PIL import Image

# ---- v2 atlas geometry (docs/pet-spec.md) ------------------------------------
CELL_W, CELL_H = 192, 208
COLS, ROWS = 8, 11

# row index -> (name, frame count, per-frame duration in ms)
STATES = [
    ("idle", 0, 6, [280, 110, 110, 140, 140, 320]),
    ("running_right", 1, 8, [120] * 7 + [220]),
    ("running_left", 2, 8, [120] * 7 + [220]),
    ("waving", 3, 4, [140] * 3 + [280]),
    ("jumping", 4, 5, [140] * 4 + [280]),
    ("failed", 5, 8, [140] * 7 + [240]),
    ("waiting", 6, 6, [150] * 5 + [260]),
    ("running", 7, 6, [120] * 5 + [220]),
    ("review", 8, 6, [150] * 5 + [280]),
]

# Alpha values below this are webp compression noise inside transparent areas.
# They are zeroed so a crop never grows to include invisible ghost pixels.
ALPHA_FLOOR = 8


def rgb565a8(cell: Image.Image) -> bytes:
    """RGB565 little-endian colour plane followed by the 8-bit alpha plane."""
    colour = bytearray()
    for r, g, b in cell.convert("RGB").get_flattened_data():
        colour += struct.pack("<H", ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))
    return bytes(colour) + cell.getchannel("A").tobytes()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--atlas", required=True, type=Path)
    ap.add_argument("--pet-id", required=True)
    ap.add_argument("--out-bin", required=True, type=Path)
    ap.add_argument("--out-header", required=True, type=Path)
    ap.add_argument("--out-source", required=True, type=Path)
    ap.add_argument("--preview-dir", type=Path, help="optional PNG contact sheet dir")
    args = ap.parse_args()

    atlas = Image.open(args.atlas).convert("RGBA")
    if atlas.size != (COLS * CELL_W, ROWS * CELL_H):
        raise SystemExit(f"atlas must be {COLS*CELL_W}x{ROWS*CELL_H}, got {atlas.size}")

    # Zero sub-threshold alpha noise before computing any bounding box.
    alpha = atlas.getchannel("A").point(lambda v: 0 if v < ALPHA_FLOOR else v)
    atlas.putalpha(alpha)

    blob = bytearray()
    frames: list[dict] = []
    states_meta: list[dict] = []

    for name, row, count, durations in STATES:
        state_frames = []
        for col in range(count):
            cell = atlas.crop(
                (col * CELL_W, row * CELL_H, (col + 1) * CELL_W, (row + 1) * CELL_H)
            )
            bbox = cell.getchannel("A").getbbox()
            if bbox is None:
                raise SystemExit(f"empty frame {name}[{col}]")
            crop = cell.crop(bbox)
            data = rgb565a8(crop)
            # 4-byte align every frame so the renderer never reads a
            # misaligned RGB565 pair out of memory-mapped flash.
            pad = (-len(blob)) % 4
            blob += b"\x00" * pad
            offset = len(blob)
            blob += data
            state_frames.append(
                {
                    "offset": offset,
                    "x": bbox[0],
                    "y": bbox[1],
                    "w": crop.width,
                    "h": crop.height,
                    "duration": durations[col],
                }
            )
        states_meta.append(
            {
                "name": name,
                "row": row,
                "first": len(frames),
                "count": count,
                "frames": state_frames,
            }
        )
        frames.extend(state_frames)

    args.out_bin.parent.mkdir(parents=True, exist_ok=True)
    args.out_bin.write_bytes(bytes(blob))

    guard = f"PET_ATLAS_{args.pet_id.upper().replace('-', '_')}_H"
    stage_x0 = min(f["x"] for f in frames)
    stage_y0 = min(f["y"] for f in frames)
    stage_x1 = max(f["x"] + f["w"] for f in frames)
    stage_y1 = max(f["y"] + f["h"] for f in frames)

    # The frame tables live in a generated .c file and are declared `extern` here,
    # so this header can be included from several translation units without
    # duplicating ~2.5 MB of tables into each object file.
    lines = [
        "// Generated by tools/gen_pet_assets.py - do not edit by hand.",
        f"// Source atlas: {args.atlas.name} (v2, {COLS*CELL_W}x{ROWS*CELL_H}, {COLS}x{ROWS})",
        f"// Frames: {len(frames)}   Blob: {len(blob)} bytes",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#ifndef " + guard,
        "#define " + guard,
        "",
        "// Union of every frame crop inside the 192x208 atlas cell. The UI keeps a",
        "// single image object this size, so the invalidated area stays constant",
        "// while the per-frame offset moves the actual pixels inside it.",
        f"#define PET_ATLAS_CELL_W        {CELL_W}",
        f"#define PET_ATLAS_CELL_H        {CELL_H}",
        f"#define PET_ATLAS_STAGE_X       {stage_x0}",
        f"#define PET_ATLAS_STAGE_Y       {stage_y0}",
        f"#define PET_ATLAS_STAGE_W       {stage_x1 - stage_x0}",
        f"#define PET_ATLAS_STAGE_H       {stage_y1 - stage_y0}",
        "",
        "// RGB565A8: 2 字节颜色平面 + 1 字节 alpha 平面。",
        "#define PET_ATLAS_BYTES_PER_PIXEL 3",
        "",
        f"#define PET_ATLAS_BLOB_SIZE {len(blob)}",
        "",
        "typedef struct {",
        "    uint32_t offset;   // byte offset of the RGB565A8 frame inside the blob",
        "    int16_t  x;        // crop origin inside the 192x208 atlas cell",
        "    int16_t  y;",
        "    int16_t  w;",
        "    int16_t  h;",
        "    uint16_t duration; // frame duration in ms",
        "} pet_atlas_frame_t;",
        "",
        "typedef struct {",
        "    const char       *name;",
        "    uint16_t          first;   // index of the first frame",
        "    uint16_t          count;",
        "    const pet_atlas_frame_t *frames;",
        "} pet_atlas_state_t;",
        "",
        f"#define PET_ATLAS_STATE_COUNT {len(states_meta)}",
        f"#define PET_ATLAS_FRAME_COUNT {len(frames)}",
        "",
        "extern const pet_atlas_state_t PET_ATLAS_STATES[PET_ATLAS_STATE_COUNT];",
        "",
        "#endif  // " + guard,
    ]
    args.out_header.write_text("\n".join(lines) + "\n")

    src = [
        "// Generated by tools/gen_pet_assets.py - do not edit by hand.",
        f'#include "pet_atlas_{args.pet_id.replace("-", "_")}.h"',
        "",
    ]
    for st in states_meta:
        src.append(
            f"static const pet_atlas_frame_t {st['name'].upper()}_FRAMES[] = {{")
        for f in st["frames"]:
            src.append(
                f"    {{ {f['offset']:8d}, {f['x']:4d}, {f['y']:4d},"
                f" {f['w']:4d}, {f['h']:4d}, {f['duration']:4d} }},"
            )
        src.append("};")
        src.append("")
    src.append("const pet_atlas_state_t PET_ATLAS_STATES[PET_ATLAS_STATE_COUNT] = {")
    for st in states_meta:
        src.append(
            f'    {{ "{st["name"]}", {st["first"]:3d}, {st["count"]:2d},'
            f" {st['name'].upper()}_FRAMES }},"
        )
    src.append("};")
    src.append("")
    args.out_source.write_text("\n".join(src) + "\n")

    if args.preview_dir:
        args.preview_dir.mkdir(parents=True, exist_ok=True)
        for st in states_meta:
            sheet = Image.new("RGBA", (CELL_W * st["count"], CELL_H), (0, 0, 0, 0))
            for i, f in enumerate(st["frames"]):
                src = atlas.crop(
                    (
                        i * CELL_W + f["x"],
                        st["row"] * CELL_H + f["y"],
                        i * CELL_W + f["x"] + f["w"],
                        st["row"] * CELL_H + f["y"] + f["h"],
                    )
                )
                sheet.paste(src, (i * CELL_W, 0))
            sheet.save(args.preview_dir / f"{st['name']}.png")

    total = sum(s["count"] for s in states_meta)
    print(f"{args.pet_id}: {total} frames, blob={len(blob):,} bytes "
          f"({len(blob)/1024/1024:.2f} MiB)")
    print(f"  bin    -> {args.out_bin}")
    print(f"  header -> {args.out_header}")
    print(f"  source -> {args.out_source}")


if __name__ == "__main__":
    main()
